### ISSUE TITLE
Full path required

### ISSUE THREAD

**Issue by dweinerATL** [hfm/puppet-remi#1]
When using your module, I get this error:

Error: Files must be fully qualified at /etc/puppet/modules/remi/manifests/rpm_gpg_key.pp:27 on node localhost.pmsolutions.local
Error: Files must be fully qualified at /etc/puppet/modules/remi/manifests/rpm_gpg_key.pp:27 on node localhost.pmsolutions.local

Line 27 is 

content => file('remi/RPM-GPG-KEY-remi'),

if I change it to

content => file('/etc/puppet/modules/remi/files/RPM-GPG-KEY-remi'),

it works

**Comment by hfm** [comment]
Resolved by #2
